name: aMetasim
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=2.7
  - gargammel
  - ms
  - seq-gen
  - numpy
  - scipy
  - biopython
  - msprime
  - r-base
  - fastqc
  - cutadapt
  - flash
  - megahit
  - kraken2
